// Code generated by mockery v1.0.0
package engine

import mock "github.com/stretchr/testify/mock"

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

// Truncate provides a mock function with given fields: table
func (_m *MockEngine) Truncate(table string) error {
	ret := _m.Called(table)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(table)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
